---
# file: sspr-classic.yml
# "classic" installation of SSPR WAR-file distribution

- hosts: sspr_hosts
  become: yes
  handlers:
    - include: handlers/handlers.yml
  roles:
    - role: java11-corretto
      tags: corretto
    - tomcat
    - sspr-classic
    - role: certbot
      when: "'certbot_hosts' in group_names"
    - role: ssl-classic
      when: "'certbot_hosts' not in group_names"
    - shibd-classic
    - httpd-classic
