---
# file: roles/sspr-classic/tasks/main.yml

- name: Create directories
  file:
    path:      "{{ item.path }}"
    owner:     "{{ item.owner }}"
    group:     "{{ item.group }}"
    mode:      "{{ item.mode }}"
    state:     directory
  with_items:
    - { path: /opt/microfocus, owner: root, group: root, mode: "u=rwX,go=rX" }
    - { path: /opt/microfocus/sspr, owner: root, group: tomcat, mode: "ug=rwX,o=rX" }
    - { path: /opt/microfocus/sspr/config, owner: root, group: tomcat, mode: "ug=rwX,o=" }

- name: SSPR file uploads
  copy:
    src:   "{{ item.src }}"
    dest:  "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode:  "{{ item.mode }}"
  notify: restart tomcat
  with_items:
    - { src: sspr.war, dest: /opt/tomcat/webapps/sspr.war, owner: root, group: tomcat, mode: "u=rw,go=r" }
    - { src: SSPRConfiguration.xml, dest: /opt/microfocus/sspr/config/SSPRConfiguration.xml, owner: root, group: tomcat, mode: "u=rw,g=r,o=" }

