---
# file: roles/sspr-classic/tasks/main.yml

- name: Create directories
  file:
    path:      "{{ item.path }}"
    owner:     "{{ item.owner }}"
    group:     "{{ item.group }}"
    mode:      "{{ item.mode }}"
    state:     directory
  with_items:
    - { path: /opt/microfocus, owner: root, group: root, mode: "u=rwX,go=rX" }
    - { path: /opt/microfocus/sspr, owner: root, group: tomcat, mode: "ug=rwX,o=rX" }
    - { path: /opt/microfocus/sspr/config, owner: root, group: tomcat, mode: "ug=rwX,o=" }

- name: SSPR file uploads
  copy:
    src:    "{{ item.src }}"
    dest:   "{{ item.dest }}"
    owner:  "{{ item.owner }}"
    group:  "{{ item.group }}"
    mode:   "{{ item.mode }}"
    backup: yes
  notify: restart tomcat
  with_items:
    - { src: sspr.war, dest: /opt/tomcat/webapps/sspr.war, owner: root, group: tomcat, mode: "u=rw,go=r" }
    - { src: "{{ sspr_config_file }}", dest: /opt/microfocus/sspr/config/SSPRConfiguration.xml, owner: root, group: tomcat, mode: "u=rw,g=r,o=" }

- name: Update motd
  ansible.builtin.template:
    src:    motd.j2
    dest:   /etc/motd
    owner:  root
    group:  root
    mode:   "u=rw,go=r"
    backup: yes
  tags: motd

- name: SSPR replace old hostname with new hostname (requires Ansible >= 2.4)
  ansible.builtin.replace:
    path: /opt/microfocus/sspr/config/SSPRConfiguration.xml
    regexp: password(-dev\.its|-uat\.its|-prod\.its)?\.carleton\.edu
    replace: "{{ sspr_nodename }}"
  ignore_errors: '{{ ansible_check_mode }}'
