# file: roles/ssl-classic/tasks/main.yml

- name: Add SSL certs and keys
  ansible.builtin.template:
    src:   "{{ item.src }}"
    dest:  "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode:  "{{ item.mode | default('u=rw,go=') }}"
    backup: yes
  with_items:
    - { src: password.carleton.edu.cer.j2, dest: "{{ ssl_certificate_file_path }}", mode: "u=rw,go=r" }
    - { src: inCommon-SHA2.pem.j2, dest: "{{ ssl_certificate_chain_file_path }}", mode: "u=rw,go=r" }
    - { src: password.carleton.edu.key.j2, dest: "{{ ssl_certificate_key_file_path }}" }
    - { src: password.carleton.edu.csr.j2, dest: /etc/pki/tls/private/password.carleton.edu.csr }
  notify: restart httpd
